sim/mahasiswa/routes.py
from email.mime import image
from flask import Flask, render_template, redirect, request, url_for, Blueprint, flash
from sim.mahasiswa.forms import Orang,login_org,Edit_org,pengaduan,edit_pengaduan,agenda_info
from sim.models import Tmahasiswa, Tpengaduan,Agenda_info
from sim import db, bcrypt,app
from flask_login import login_user,current_user,logout_user,login_required
import os
import secrets
from PIL import Image



rmahasiswa=Blueprint('rmahasiswa', __name__)

@rmahasiswa.route("/")
def rumah():
    return render_template("rumah.html")

@rmahasiswa.route("/tentang")
def tentang():
    return render_template("tentang.html")

@rmahasiswa.route("/daftar", methods=['GET', 'POST'])
def daftar():
    form=Orang()
    if (form.validate_on_submit()):
        pas_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')# ini adalah variabel yang akan mengamankan pasword yang dimasukan dan nanti pasword yang sudah di amankan akan di panggil di line selanjutnya
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data, password=pas_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar', 'primary')
      
        return redirect(url_for('rmahasiswa.login'))
    return render_template("daftar.html", form=form)

@rmahasiswa.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.rumah'))
    form=login_org()
    if form.validate_on_submit():
        ceknpm= Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akun'))
        else:
            flash('Login Gagal, Periksa NPM dan Password kembali', 'danger')
    return render_template ("login.html",form=form)


@rmahasiswa.route("/akun")
@login_required # ini akan membuat halamanya hanya bisa dibuka saat user sudah login
def akun():
    return render_template('akun.html')

@rmahasiswa.route("/keluar")
def keluar():
    logout_user()
    return redirect(url_for('rmahasiswa.rumah'))

@rmahasiswa.route("/edit", methods=['GET','POST'])
@login_required
def edit():
    form = Edit_org()
    if form.validate_on_submit():# ini adalah sintak untuk mengupdate data yang akan dimasukan ke dalam database
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto=file_foto
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        sandi = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.password=sandi
        db.session.commit()
        flash('Data berhasil di rubah ','warning ')
        return redirect(url_for('rmahasiswa.edit'))
    elif request.method=="GET":# ini sintak untuk menampilkan data ke dalam database
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama 
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
        form.password.data=current_user.password
        
    return render_template ('edit.html',form=form)

#simpan foto 
def simpan_foto(form_foto):
    form = Edit_org()
    random_hex=secrets.token_hex(8  )
    f_name,f_ext=os.path.splitext(form_foto.filename)
    foto_fn = random_hex + f_ext
    foto_path = os.path.join(app.root_path,'sim/static/foto',foto_fn)# ini akan menyimpan foto yang diposting user
    # form_foto.save(foto_path)
    j = Image.open(form_foto)
    ubah_size=(300,300)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    
    return foto_fn

@rmahasiswa.route("/laporan", methods=['GET','POST'])
@login_required
def laporan():
    dt_pengaduan = Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form = pengaduan()
    if form.validate_on_submit():
        
        add_laporan = Tpengaduan(subjek=form.subjek.data,kategori=form.kategori.data,detail_pengaduan=form.detail_pengaduan.data,mahasiswa=current_user)
        db.session.add(add_laporan)
        db.session.commit()
        flash('laporan telah diterima ','warning ')
        return redirect(url_for('rmahasiswa.laporan'))        
       
    return render_template('laporan.html',form=form,dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/editlaporan/<int:ed_id>/update", methods=['GET','POST'])
@login_required # ini akan membuat halamanya hanya bisa dibuka saat user sudah login
def edit_lapor(ed_id):# ed_id adalah id yang ada di database dan data yang di edit akan berdasarkan id nya
    form = edit_pengaduan()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":# ini adalah sytak untuk menampilkan data 
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    elif form.validate_on_submit():# ini sytak untuk mengubah data di dalam database
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Laporan telah direvisi :)','warning')
        return redirect(url_for('rmahasiswa.laporan'))
    return render_template('editlaporan.html',form=form)

@rmahasiswa.route("/delete/<id>", methods=['GET','POST'])
@login_required # ini akan membuat halamanya hanya bisa dibuka saat user sudah login
def cabut_lapor(id):
    hapus =Tpengaduan.query.get(id)
    db.session.delete(hapus)
    db.session.commit()
    flash('Laporan telah sudah dicabut :)','warning')
    return redirect(url_for('rmahasiswa.laporan'))

@rmahasiswa.route("/posting", methods=['GET','POST'])
@login_required
def agenda_inf():
    form = agenda_info()
    if form.validate_on_submit(): 
        add_agenda = Agenda_info(subjek=form.subjek.data,caption=form.caption.data)
        db.session.add(add_agenda)
        db.session.commit()
        flash('Sudah di posting ','warning ')
        return redirect(url_for('rmahasiswa.agenda_inf'))  
    return render_template('tambahagenda.html',form=form)#, info_agenda=info_agenda)

@rmahasiswa.route("/agenda", methods=['GET','POST'])
def informasi():
    info_agenda = Agenda_info.query.all()
    
    return render_template("agenda_info.html",info=info_agenda)

sim/templates/agenda_info.html
{% extends "base.html" %}

{% block konten %}

{% for data in info %}

<div class="card" style="width: 40em;">
   <div class="card-body">
     <h5 class="card-title">{{data.subjek}} </h5>
     <h6 class="card-subtitle mb-2 text-muted">di post pada {{data.tgl_post}} </h6>
     <p class="card-text"> {{data.caption}} </p>
     <a href="#" class="card-link">Like</a>
     <a href="#" class="card-link">Komen</a>


   </div>
 </div>

{% endfor %}

{% endblock %}

sim/templates/akun.html
{% extends "base.html" %}

{% block konten %}

<div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
    <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
      <h1 class="display-4">Hello,{{current_user.nama}} </h1>  
      
        <h1 class="display-4">selamat datang !</h1>
        <p class="lead">aku tak tau apa tujuanmu mengunjungi website ini tapi semoga kau betah </p>
        <hr class="my-4">
        <p>Jika ingin melapor sesuatu klik link di bawah</p>
        <a class="btn btn-primary btn-lg" href="{{url_for('rmahasiswa.laporan')}}" role="button">Lapor</a>
      </div>
    
</div>

{% endblock %}

sim/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Halo semua</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename="css/bootstrap.min.css")}}"><!--ini adalah cara untuk memanggil bootstrap-->
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename="css/style.css")}}"><!--ini adalah cara untuk memanggil bootstrap-->

    
    
</head>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
            
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for("rmahasiswa.rumah")}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for("rmahasiswa.informasi")}}">Informasi</a>
              </li>
              
              {% if current_user.is_authenticated %}    
              <li class="nav-item">
                <a class="nav-link" href="{{url_for("rmahasiswa.agenda_inf")}}">Posting</a>
              </li>   
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for("rmahasiswa.daftar")}}">Daftar</a></li>
              <!-- ini akan ditampilkan saaat tidak login -->
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for("rmahasiswa.login")}}">Login</a></li>
              {%endif%}
            </ul>

            </div>
            <div col-md-7>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>

            </div>
          </div>
        </div>
 
      
      </nav>

      
      
      <div class="container mt-4">

        <div class="row"><!--ini adalah layout jadi nanti halaman webnya diatur seperti tabel dan ini untuk membuat sebuah baris-->
          <div class="col-md-8"><!--jika di atas itu baris maka yang ini adalah kolomnya dan kolom itu batasnya 12-->
            <div class="shadow p-3 mb-5 bg- rounded">
              <!-- flash -->
              {% with messages= get_flashed_messages(with_categories=true) %}
              {% if messages %}
              {% for category, message in messages %}

              <div class="alert alert-{{category}}">
                  {{message}}
              </div>
              {% endfor %}
              {% endif %}
              {% endwith %}

            </div>  
            {% block konten %}
              
            {% endblock %}
        </div>
        
        <div class="col-md-4"><!--karena di atas sudah terpakai 8 maka sisanya 4 dipakai di sini-->
        <div class="shadow p-3 mb-5 bg- rounded">
          {% if current_user.is_authenticated %}
          <div class="card" style="width: 19rem;">
            <img src="{{url_for('static', filename= 'foto/'+current_user.foto )}} " class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{current_user.nama}}</h5>
              <p class="card-text">{{current_user.email}}</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="{{url_for('rmahasiswa.akun')}}">dashboard</a> </li>
              <li class="list-group-item">Ed</li>
              <li class="list-group-item">
                <a href="{{url_for('rmahasiswa.laporan')}}">lapor</a>
              </li>
            </ul>
            <div class="card-body">
              <a href="{{url_for('rmahasiswa.edit')}}" class="card-link">Update Profil</a>
              <a href="{{url_for('rmahasiswa.keluar')}}" class="card-link">Keluar</a>
            </div>
          </div>
          
          {% else %}
          
          <h1>Menu Lain</h1>         
          <li>data mahasiswa</li>
          <li>data dosen</li>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
        
      
    
    
  </body>
  

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="{{url_for ('static',filename="js/bootstrap.min.js")}}" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  
  
  <!-- <script src="../static/js/bootstrap.min.js"></script> -->

</html>

sim/templates/coba.html
{% extends "base.html" %}

{% block konten %}

<div class="row"><!-- clas row ini nanti berguna untuk oembagian column di bawah ini -->
    <div class="col-md-11"> <!-- angka 11 itu adalah ukuran kolomya maks 12 nanti di bagi dengan tag div di bawah -->
        
        <h1>anjay</h1>
    </div>

    <div class="col-md-1"><!-- 1 itu sisa dari 11 di atas -->
        <h1>anjay</h1>
    </div>
</div>

{% endblock %}

sim/templates/daftar.html
{% extends "base.html" %}

{% block konten %}
<h1>Formulir Pendaftaran </h1>

<form method="POST">
   <div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
      <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
         
         {{form.hidden_tag()}}
         <div class="form-group">
            {{form.npm.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
            {% if form.npm.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.npm(class="form-control is-invalid")}}
         <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
         </div>
      
         {% else %}<!--ini else-->
         {{form.npm(class="form-control")}}<!--ini juga sama kyak di atas-->
         
      {% endif %}</div>
      
   <div class="form-group">
      {{form.nama.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.nama(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 
   <div class="form-group">
      {{form.email.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.email(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>

   
   
   
   <div class="form-group">
      {{form.kelas.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.kelas(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 
  <div class="form-group">
      {{form.alamat.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.alamat(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 

   
      {{form.hidden_tag()}}
      <div class="form-group">
         {{form.password.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
         {% if form.password.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.password(class="form-control is-invalid")}}
         <div class="invalid-feedback">
         {% for error in form.password.errors %}
         <span>{{error}}</span>
         {% endfor %}
         </div>

         {% else %}<!--ini else-->
         {{form.password(class="form-control")}}<!--ini juga sama kyak di atas-->

         {% endif %}</div>
      

      {{form.hidden_tag()}}
      <div class="form-group">
         {{form.konfir_pass.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
         {% if form.konfir_pass.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.konfir_pass(class="form-control is-invalid")}}
         <div class="invalid-feedback">
         {% for error in form.konfir_pass.errors %}
         <span>{{error}}</span>
         {% endfor %}
         </div>

         {% else %}<!--ini else-->
         {{form.konfir_pass(class="form-control")}}<!--ini juga sama kyak di atas-->

         {% endif %}</div>
      
      

   <div class="form-group">
      
      {{form.submit(class="btn btn-primary")}}<!--ini juga sama kyak di atas-->
   </div>
  
   

   </div>
</div>

</form>


{% endblock %}

sim/templates/data_orang.html
{% extends "base.html" %}

{% block konten %}
  <form>
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
        {{form.npm(class="form-control")}}<!--ini juga sama kyak di atas-->
     </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>



<h1>Ini adalah Data orang!!!!!!!!!!!!</h1>
	<h2>Data Manusia :</h2>
    {% for data in anjay %} <!-- ini adalah statement untuk awal looping  -->
    <ul>
        <li><label for="">Nama:</label> {{data.nama}}</li>
        <li><label for="">Gender</label> {{data.gender}}</li>
        <li><label for="">Spesies</label> {{data.spesies}}</li><br>
    </ul>
    {% endfor %} <!-- ini adalah akhir looping (kalo di java anggap saja ini tutup kurung kuawalnya ) -->
{% endblock %}

sim/templates/edit.html
{% extends "base.html" %}

{% block konten %}
<h1>Update Profil </h1>

<form method="POST" enctype="multipart/form-data">
   <div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
      <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
         
         {{form.hidden_tag()}}
         <div class="form-group">
            {{form.npm.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
            {% if form.npm.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.npm(class="form-control is-invalid")}}
         <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
         </div>
      
         {% else %}<!--ini else-->
         {{form.npm(class="form-control")}}<!--ini juga sama kyak di atas-->
         
      {% endif %}</div>
      
   <div class="form-group">
      {{form.nama.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.nama(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 
   <div class="form-group">
      {{form.email.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.email(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>

   
   
   
   <div class="form-group">
      {{form.kelas.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.kelas(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 
  <div class="form-group">
      {{form.alamat.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
      {{form.alamat(class="form-control")}}<!--ini juga sama kyak di atas-->
   </div>
 

   
      {{form.hidden_tag()}}
      <div class="form-group">
         {{form.password.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
         {% if form.password.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.password(class="form-control is-invalid")}}
         <div class="invalid-feedback">
         {% for error in form.password.errors %}
         <span>{{error}}</span>
         {% endfor %}
         </div>

         {% else %}<!--ini else-->
         {{form.password(class="form-control")}}<!--ini juga sama kyak di atas-->

         {% endif %}</div>
      

      {{form.hidden_tag()}}
      <div class="form-group">
         {{form.konfir_pass.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
         {% if form.konfir_pass.errors %}<!--ini percabangan jika menemukan eror-->
         {{form.konfir_pass(class="form-control is-invalid")}}
         <div class="invalid-feedback">
         {% for error in form.konfir_pass.errors %}
         <span>{{error}}</span>
         {% endfor %}
         </div>

         {% else %}<!--ini else-->
         {{form.konfir_pass(class="form-control")}}<!--ini juga sama kyak di atas-->

         {% endif %}</div>
      
      
      {{form.hidden_tag()}}
      <div class="form-group">
            {{form.foto.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
            {% if form.foto.errors %}<!--ini percabangan jika menemukan eror-->
            {{form.foto(class="form-control is-invalid")}}
            <div class="invalid-feedback">
            {% for error in form.foto.errors %}
            <span>{{error}}</span>
            {% endfor %}
            </div>
   
            {% else %}<!--ini else-->
            {{form.foto(class="form-control")}}<!--ini juga sama kyak di atas-->
   
      {% endif %}</div>
         

   <div class="form-group">
      
      {{form.submit(class="btn btn-primary")}}<!--ini juga sama kyak di atas-->
   </div>
  
   

   </div>
</div>

</form>


{% endblock %}

sim/templates/laporan.html
{% extends "base.html" %}

{% block konten %}

<div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
    <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
        
        <h3>Pelaporan</h3>
        <!-- form pelaporan ini sama saja dengan daftar.html tapi tentu saja di modif -->
        <form method="POST">
            <div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
               <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
                  
                  {{form.hidden_tag()}}
                  <div class="form-group">
                     {{form.subjek.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
                     {% if form.subjek.errors %}<!--ini percabangan jika menemukan eror-->
                  {{form.subjek(class="form-control is-invalid")}}
                  <div class="invalid-feedback">
                     {% for error in form.subjek.errors %}
                     <span>{{error}}</span>
                     {% endfor %}
                  </div>
               
                  {% else %}<!--ini else-->
                  {{form.subjek(class="form-control")}}<!--ini juga sama kyak di atas-->
                  
               {% endif %}</div>

               <!-- kategori ini tampilannya sama dengan tag select dan option di html-->
               <div class="form-group">
                {{form.kategori.label(class="form-control-label")}}
                {% if form.kategori.errors %}
                {{form.kategori(class="form-control is-invalid")}}
                 <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
                     <span>{{error}}</span>
                {% endfor %}
                 </div>
          
                {% else %}
                {{form.kategori(class="form-control")}}
             
                  {% endif %}
               </div>

               <!-- detail pengaduan -->
               <div class="form-group">
                {{form.detail_pengaduan.label(class="form-control-label")}}<!--tanda kurung ini berguna untuk menggunakan clas yang ada di css/bootstrap-->
                {% if form.detail_pengaduan.errors %}<!--ini percabangan jika menemukan eror-->
                {{form.detail_pengaduan(class="form-control is-invalid")}}
                 <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
                     <span>{{error}}</span>
                {% endfor %}
                 </div>
          
                {% else %}
                {{form.detail_pengaduan(class="form-control")}}
             
                  {% endif %}
               </div>

           
               
               
         
            <div class="form-group">
               
               {{form.submit(class="btn btn-primary")}}<!--ini juga sama kyak di atas-->
            </div>
           
            
         
            </div>
         </div>
         
         </form>

        <hr class="my-4">
        <h4>Data Pelaporan para cepu</h4>
        <table class="table table-responsive">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Tanggal</th>
      <th scope="col">Subjek</th>
      <th scope="col">kategori</th>
      <th scope="col">detail_laporan</th>
      <th scope="col">id</th>
      <th scope="col">edit</th>
      <th scope="col">hapus</th>
    </tr>
  </thead>
  <tbody>
   {% for data in dt_pengaduan %}
    <tr>
      <th scope="row"></th>
      <td>{{data.tgl_post}} </td>
      <td>{{data.kategori}} </td>
      <td>{{data.subjek}} </td>
      <td>{{data.detail_pengaduan}} </td>
      <!-- mahasiswa itu di dapat dari backref di models.py -->
      <td>{{data.mahasiswa.nama  }}</td>
      <th scope="col"><a  class="btn btn-outline-dark" href="{{url_for('rmahasiswa.edit_lapor',ed_id=data.id)}} ">edit</a></th>
      <th scope="col"><a  class="btn btn-outline-danger" href="/delete/{{data.id}}" onclick="return confirm('ini mo hapus da?') ">hapus</a></th>
    </tr>
   {% endfor %}
  </tbody>
</table>
      </div>
    
</div>

{% endblock %}

sim/templates/login.html
{% extends "base.html" %} 
{% block konten %}
<h1>Login Mahasiswa</h1>

<form method="POST">
  {{form.hidden_tag()}}
  <div class="form-group">
    {{form.npm.label(class="form-control-label")}} {% if form.npm.errors %} {{form.npm(class="form-control is-invalid")}}

    <div class="invalid-feedback">
      {% for error in form.npm.errors %}
      <span> {{error}}</span>

      {% endfor %}
    </div>
    {%else%} {{form.npm(class="form-control")}} {%endif%}
  </div>

  <div class="form-group">
    {{form.password.label(class="form-control-label")}} {% if form.password.errors %} {{form.password(class="form-control is-invalid")}}

    <div class="invalid-feedback">
      {% for error in form.password.errors %}
      <span> {{error}}</span>

      {% endfor %}
    </div>
    {%else%} {{form.password(class="form-control")}} {%endif%}
  </div>

  <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>

  <span><a href="{{url_for('rmahasiswa.daftar')}}">Daftar Akun</a></span>
</form>

{% endblock %}

sim/templates/rumah.html
{% extends "base.html" %}

{% block konten %}

<div class="container"><!--ini container ini berguna agar isi webnya di tengan -->
    <div class="jumbotron"><!--jumbroton ini akan di edit fi file style.css yang ada di dalam forder static dan di dalam folder css-->
        <h1 class="display-4">Halo.......</h1>
        <p class="lead">ini adalah website dari hasil belajar di mata kuliah pemograman web</p>
        <hr class="my-4">
        <p>akhirnya setelah banyar eror jadi juga :,)</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </div>
    
</div>

{% endblock %}